# parameters:
# - name: Build
#   type: string
# steps:
#   - script: echo I did a thing
#     condition:  eq('${{ variables.Build }}', 'Java')
#   - template: JavaTemplate.yml

# - ${{ if eq(variables.Build, 'Java') }}:
#   - template: JavaTemplate.yml
# - ${{ if eq(variables.Build, 'dotnet') }}:
#   - template: dotnetTemplate.yml
stages:
- stage: A
  condition:  eq('${{ variables.Build }}', 'Java')
  jobs:
  - job:
    steps:
      - template: JavaTemplate.yml
