trigger: none
resources:
  repositories:
    - repository: ProjectDemo
      type: git
      name: ProjectDemo
prameters:
- name: ${{ variables.Build }}
- name: ${{ variables.sonarQubeRunAnalysis }}
- name: ${{ variables.Docker }}
variables:
- template: variables.yml@ProjectDemo
steps:
- ${{ if eq(variables.Build, 'Java') }}:
  - ${{ if eq(variables.sonarQubeRunAnalysis, true) }}:
    - template: sonarcloudprepare.yml
  - template: MavenBuild.yml
  - ${{ if eq(variables.sonarQubeRunAnalysis, true) }}:
    - template: SonarCloud.yml
  - ${{ if eq(variables.Docker, true) }}:
    - template: Docker.yml
  - template: PublishArtifact.yml
- ${{ if eq(variables.Build, 'dotnet') }}:
  - template: dotnetTemplate.yml
