trigger: none
resources:
  repositories:
    - repository: ProjectDemo
      type: git
      name: ProjectDemo
variables:
- template: variables.yml@ProjectDemo
steps:
- ${{ if eq(parameters.Build, 'Java') }}:
  - ${{ if eq(parameters.sonarQubeRunAnalysis, true) }}:
    - template: sonarcloudprepare.yml
  - template: MavenBuild.yml
  - ${{ if eq(parameters.sonarQubeRunAnalysis, true) }}:
    - template: SonarCloud.yml
  - ${{ if eq(parameters.Docker, true) }}:
    - template: Docker.yml
  - template: PublishArtifact.yml
- ${{ if eq(variables.Build, 'dotnet') }}:
  - template: dotnetTemplate.yml
